version: '3'

services:
  go:
    image: golang:latest
    command: tail -F /dev/null
    working_dir: /usr/app/src
    volumes:
      - .:/usr/app
    environment:
      - GOROOT=/usr/local/go
      - GOPATH=/usr/app
    ports:
      - "3000:3000"
    restart: always
