version: '3.7'

services:
  go:
    build:
      context: ./docker
      dockerfile: Dockerfile
    working_dir: /go-microservices
    volumes:
      - .:/go-microservices
    ports:
      - "3000:3000"
      - "3001:3001"
